"""delivery types: text, file, manual

Revision ID: c1d507b48429
Revises: f5a2d7d1cc1c
Create Date: 2026-08-10 11:50:06.037912
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c1d507b48429'
down_revision: str | None = 'f5a2d7d1cc1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_type', sa.String(length=16), server_default='text', nullable=False))
    op.add_column('products', sa.Column('delivery_type', sa.String(length=16), server_default='text', nullable=False))
    op.add_column('stock_items', sa.Column('file_id', sa.String(length=255), nullable=True))
    op.add_column('stock_items', sa.Column('file_kind', sa.String(length=16), nullable=True))
    op.add_column('stock_items', sa.Column('file_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'file_name')
    op.drop_column('stock_items', 'file_kind')
    op.drop_column('stock_items', 'file_id')
    op.drop_column('products', 'delivery_type')
    op.drop_column('orders', 'delivery_type')
    # ### end Alembic commands ###
