"""initial schema

Revision ID: f5a2d7d1cc1c
Revises: 
Create Date: 2026-08-10 04:41:57.745298
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f5a2d7d1cc1c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('user_id', name='uq_admins_user_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_table('balance_txns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_kop', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_kop', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_txns')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_balance_txns_user_id_created_at', 'balance_txns', ['user_id', 'created_at'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=16), server_default='text', nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('blocked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_broadcasts_status', 'broadcasts', ['status'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_categories_sort_order', 'categories', ['sort_order'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_ref', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('invite_url', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_channels_sort_order', 'channels', ['sort_order'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.BigInteger(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('per_user_limit', sa.Integer(), server_default='1', nullable=True),
    sa.Column('min_order_kop', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes')),
    sa.UniqueConstraint('code', name='uq_promo_codes_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('hint', sa.String(length=255), nullable=True),
    sa.Column('value_type', sa.String(length=16), server_default='str', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('texts',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('hint', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_texts')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('lang', sa.String(length=8), server_default='ru', nullable=False),
    sa.Column('balance_kop', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('block_reason', sa.String(length=255), nullable=True),
    sa.Column('has_blocked_bot', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id', name=op.f('pk_users')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_table('broadcast_targets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], name=op.f('fk_broadcast_targets_broadcast_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_targets')),
    sa.UniqueConstraint('broadcast_id', 'user_id', name='uq_broadcast_targets_broadcast_id_user_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_broadcast_targets_broadcast_id_status', 'broadcast_targets', ['broadcast_id', 'status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_kop', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('image_file_id', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_products_category_id_sort_order', 'products', ['category_id', 'sort_order'], unique=False)
    op.create_index('ix_products_title', 'products', ['title'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='purchase', nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_title', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price_kop', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_kop', sa.BigInteger(), nullable=False),
    sa.Column('discount_kop', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_kop', sa.BigInteger(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.Column('promo_code', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('provider_txn_id', sa.String(length=128), nullable=True),
    sa.Column('pay_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('reserve_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('admin_note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_orders_product_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], name=op.f('fk_orders_promo_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('provider', 'provider_txn_id', name='uq_orders_provider_provider_txn_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_user_id_created_at', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_table('promo_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_promo_scopes_category_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_promo_scopes_product_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], name=op.f('fk_promo_scopes_promo_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_scopes')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_promo_scopes_promo_id', 'promo_scopes', ['promo_id'], unique=False)
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('items_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_batches_product_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_batches')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_stock_batches_product_id', 'stock_batches', ['product_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=128), nullable=True),
    sa.Column('amount_kop', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='RUB', nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_provider_provider_txn_id', 'payments', ['provider', 'provider_txn_id'], unique=False)
    op.create_table('promo_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_promo_uses_order_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], name=op.f('fk_promo_uses_promo_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_uses')),
    sa.UniqueConstraint('promo_id', 'order_id', name='uq_promo_uses_promo_id_order_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_promo_uses_promo_id_user_id', 'promo_uses', ['promo_id', 'user_id'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='available', nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('reserved_until', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('defect_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], name=op.f('fk_stock_items_batch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_items_product_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_items')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_stock_items_order_id', 'stock_items', ['order_id'], unique=False)
    op.create_index('ix_stock_items_product_id_status', 'stock_items', ['product_id', 'status'], unique=False)
    op.create_index('ix_stock_items_status_reserved_until', 'stock_items', ['status', 'reserved_until'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('replaced_by_item_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], name=op.f('fk_order_items_stock_item_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('order_id', 'stock_item_id', name='uq_order_items_order_id_stock_item_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)

    # Номера заказов начинаются с пятизначного: «#10001» читается как номер,
    # «#1» — как тестовый прогон. Значение стартовое, дальше MySQL ведёт сам.
    op.execute("ALTER TABLE orders AUTO_INCREMENT = 10000")


def downgrade() -> None:
    # Индексы отдельно НЕ удаляются.
    #
    # Автогенератор Alembic сначала снимает индексы, потом таблицы. В MySQL это
    # не работает: индекс по колонке внешнего ключа обязателен, пока сам ключ
    # существует, и `DROP INDEX ix_stock_items_product_id_status` падает с
    # ошибкой 1553. `DROP TABLE` снимает и таблицу, и её индексы разом.
    #
    # Порядок обратный созданию: сначала таблицы, которые ссылаются, потом те,
    # на которые ссылаются.
    for table in (
        "order_items",
        "stock_items",
        "promo_uses",
        "payments",
        "stock_batches",
        "promo_scopes",
        "orders",
        "products",
        "broadcast_targets",
        "users",
        "texts",
        "settings",
        "promo_codes",
        "channels",
        "categories",
        "broadcasts",
        "balance_txns",
        "audit_log",
        "admins",
    ):
        op.drop_table(table)
